version: '3'

services:
  nginx:
    image: nginx:alpine
    hostname: 'ssl-get.site'
    environment:
      - "NODE_ENV=production"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - front_html:/usr/share/nginx/html
      - ./nginx/ssl:/etc/ssl
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
      - front
    restart: always

  api:
    build: ./back
    ports:
      - '5000'
    restart: always 

  front:
    build: ./front
    volumes:
      - front_html:/app/build
    environment:
      - "NODE_ENV=production"
    ports:
      - '3000'
volumes:
  front_html: