version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./Config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Config/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - '80:80'
    depends_on:
      - api
    restart: always

  api:
    build: .
    ports:
      - '5000'
    restart: always