FROM node:10 AS builder

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm i
RUN npm install react-scripts@3.4.1 -g --silent

# start app
CMD ["npm", "run", "start"]